### PR TITLE
Feature/design 14

### PR DESCRIPTION
**Pull request by CarterLankford**
Created UML design for this project. Seeking review before starting on code for project.

### CODE REVIEW

**Review by vinceynhz — CHANGES_REQUESTED** [review]
On larger applications we can skip getters and setters, but for educational purposes I'd suggest adding them on this diagram.

This will help me know how you intend to have these clases interacting with each other :)

**Employee**
- The word `employee` can be removed from the properties `employeeName` and `employeeId` as it is redundant.
- This class should offer a method to calculate the payment per narrative:
> Each eamployee has also a way to calculate how much they will get paid every week
- Not all employees have _clock thresholds_ nor _clock threshold penalties_

**SalaryEmployee**
- The following properties are defined at the object level, can they change or are they going to hold the same value for all instances of the class? `allowedVacationDay`, `missedDayDeductions`, `maxMissedDaysAllowed`, `clockThreshold`
- The calculatePay method should be inherited from `Employee`

**HourlyEmployee**
- Same question as in `SalaryEmployee`, the following properties are defined at the instance level, can they change or will they be the same across instances? `minimumHours`, `maximumHours`
- Per narrative, hourly employees cannot check in before their scheduled start time, nor after it (`canClockEarly`)
- Add a UML note describing how are you planning to keep track of 
the worked hours.

**TaskEmployee**
- If all task employees are allowed to clock before the time allocated for the task, does it make sense to have a flag (`canClockEarly`) to say so? See this on [redundant variables](https://www.yegor256.com/2015/09/01/redundant-variables-are-evil.html)
- The `TaskEmployee` should have some attribute to say which task is being assigned to them. From that assignment of task the scheduled start and end time should be updated.
- Add a UML note describing how do you plan to mark the task as completed.
- Typo on 'latePenalatyCount'
- Same question from `SalaryEmployee` and `HourlyEmployee` but in this class about `lateTimeThreshold`.
- `collectPayment` should be named after the same method to get and calculate payment that it's inherited from `Employee`

**StoreOperators**
- The coordinator bonus only applies to `SalaryEmployee`, per narrative, hourly employees cannot be coordinators
- From narrative this is not explicit, but if you follow the text all Employees have a department, only Hourly and Salary are allowed to change department (as a hint: check the Triangle classes from Geometry).

**Management**
- The name of the method could be a little bit more expressive, suggestions: `getWeeklyReport()` `generateWeeklyReport()`

**DepartmentManager**
- Add a UML note explaining how the interactions between `DepartmentManager`, `Task` and `TaskEmployee` work when creating tasks and hiring people for them.

**Comment by CarterLankford** [comment]
#### Employee
> * The word employee can be removed from the properties employeeName and employeeId as it is redundant.  

Removed the "employee" prefix on the variables

> * This class should offer a method to calculate the payment per narrative:
Each employee has also a way to calculate how much they will get paid every week

The method has been added in. My thinking is that, per class, the methods could override the parent class for what is needed. 

> * Not all employees have clock thresholds nor clock threshold penalties

Remove the clock thresholds and clock penalties for the classes that shouldn't have them. 

#### SalaryEmployee
> * The following properties are defined at the object level, can they change or are they going to hold the same value for all instances of the class? allowedVacationDay, missedDayDeductions, maxMissedDaysAllowed, clockThreshold

The allowedVacationDays, missedDayDeductions, maxMissedDaysAllowed, clockThreshold have all been changed to constants, since they won't be adjusted ever. 

> * The calculatePay method should be inherited from Employee

Corrected

#### HourlyEmployee
> * Same question as in SalaryEmployee, the following properties are defined at the instance level, can they change or will they be the same across instances? minimumHours, maximumHours

These were also adjusted. 

> * Per narrative, hourly employees cannot check in before their scheduled start time, nor after it (canClockEarly)

canClockEarly was removed.  The idea is to have the clockIn method check to see if the user is allowed to check in and if so log the time. 

> * Add a UML note describing how are you planning to keep track of the worked hours.

Done, this caused me to adjust the hoursWorked variable to a float, since they won't always work full hours. 

#### TaskEmployee
> * If all task employees are allowed to clock before the time allocated for the task, does it make sense to have a flag (canClockEarly) to say so? See this on redundant variables

It's been removed. 

> * The TaskEmployee should have some attribute to say which task is being assigned to them. From that assignment of task the scheduled start and end time should be updated.

Added in assignedTask variable and method to assign task with a return of boolen to make sure it's successfully assigned. 

> * Add a UML note describing how do you plan to mark the task as completed.

This has been done. 

> * Typo on 'latePenalatyCount'

Typo corrected

> * Same question from SalaryEmployee and HourlyEmployee but in this class about lateTimeThreshold.

Same correction as before

> * collectPayment should be named after the same method to get and calculate payment that it's inherited from Employee

This has been done. 

#### StoreOperators
> * The coordinator bonus only applies to SalaryEmployee, per narrative, hourly employees cannot be coordinators

Removed from store ops and put the variable in Salary as a constant, the boolean that marks if they are a coordinator is set to false when class is created. 

> * From narrative this is not explicit, but if you follow the text all Employees have a department, only Hourly and Salary are allowed to change department (as a hint: check the Triangle classes from Geometry).

Believe to have corrected this but am not 100% sure. 

#### Management
> * The name of the method could be a little bit more expressive, suggestions: getWeeklyReport() generateWeeklyReport()

Used your second suggestion :)

#### DepartmentManager
> * Add a UML note explaining how the interactions between DepartmentManager, Task and TaskEmployee work when creating tasks and hiring people for them.

Done.

**Review by vinceynhz — CHANGES_REQUESTED** [review]
- All methods are missing the type of the arguments:
`[+|-|#] methodName(arg1 : Type, arg2: Type ...) : Type`

- What is the body of `Employee.calculatePay()`? 

- You should not be allowed to change an Employee's id, per narrative it's defined when the employee is hired (i.e. the Employee is created).

- Normally, when you have an abstract class (such as Employee), the constructor is marked as `protected` (`#` in UML), because only the children can call that constructor (using `super(...)`), and you can't do `Employee a = new Employee(...)`

- What is the difference between `Employee.clockIn()` and `Employee.setClockInTime(clockInTime)`?

- What is the body for `Employee.getMaxMissedDaysAllowed()`? What happens with that method if called from an `HourlyEmployee` instance?

- At this point in our application, you can't change the maximum number of missed days allowed for any Employee (or employee subtype).

- On `TaskEmployee`, `departmentName` it's already defined in the parent class.

- For `SalaryEmployee` the normal convention on boolean attributes is to call the getter `is*` and the attribute just the name of the flag, for example:
`- coordinator : boolean = false`
`+ isCoordinator(): boolean`

- On `Task` what is the difference between `completeTask()` and `setComplete()`?

- On `Task` you shouldn't be allowed to change if the employee has been paid after the fact. For example, your class should provide a mechanism to say "this task is completed and paid", but you should not be able to change the task back to be unpaid - this would be fraudulent.

- You marked the implementation of `Management.generateWeeklyReport()` on implementing classes, but not for `StoreOperators`

- `StoreOperators.changeDepartment()` is not needed, the narrative only asks for a way to allow those Employees to change department and `Employee.setDepartmentName()` already covers that case.

- The UML notes required on the first review have not been added. Please see this for reference: https://image.slidesharecdn.com/introuml-1227807688880463-8/95/intro-uml-33-728.jpg?cb=1227779735

In general this looks very good, addressing above changes should be enough to get ready to write the code.

**Comment by CarterLankford** [comment]
> * All methods are missing the type of the arguments: 

I've added those into the UML diagram. 

> * What is the body of `Employee.calculatePay()` ?

It has been changed to an abstract method and will remain empty, since all child classes will have different ways of calculating this amount. 

> * You should not be allowed to change an Employee's id, per narrative it's defined when the employee is hired (i.e. the Employee is created).

I removed the setId from the diagram but left in the getId. We can set the id value when the object is constructed. 

> * Normally, when you have an abstract class (such as Employee), the constructor is marked as `protected` (`#` in UML), because only the children can call that constructor (using `super(...)`), and you can't do `Employee a = new Employee(...)`

Employee class has had it's constructor changed from public to protected. 

> * What is the difference between `Employee.clockIn()` and `Employee.setClockInTime(clockInTime)`?

There isn't a difference and is redundant, thank you for catching that! I removed both `Employee.clockIn()` and `Employee.clockOut()`

> * What is the body for `Employee.getMaxMissedDaysAllowed()`? What happens with that method if called from an `HourlyEmployee` instance?

There is nothing in the body for `Employee.getMaxMissedDaysAllowed()` any longer since it's been removed.  Since not all child classes need to track this value it's methods and variable have been removed from the `Employee` class. 

> * At this point in our application, you can't change the maximum number of missed days allowed for any Employee (or employee subtype).

This further elaborates the need to remove the method as stated in the above response. It now lives in the `SalaryEmployee` class. It only has a get method but other than that has been set to a static int value of 4. This is because all salary members can miss a max amount of 4 days before they lose all their weekly pay. 

> * On `TaskEmployee`, `departmentName` it's already defined in the parent class. 

It has been sent to the nether!

> * For `SalaryEmployee` the normal convention on boolean attributes is to call the getter `is*` and the attribute just the name of the flag, for example:
`- coordinator : boolean = false`
`+ isCoordinator(): boolean`

Modified as suggested, and for the setter I added the method `SalaryEmployee.setIsCoordinator()` and added a note to the uml to describe how I would expect it to be used. So that you don't have to see the uml to hear the idea here it is: "when using `SalaryEmployee.setIsCoordinator` we can have it always set to the inverse of the current value of coordinator.  If a check of value is ever needed, the `SalaryEmployee.isCoordinator` method should be called."  

I was curious if the type of this shouldn't be public but rather protected so that the other salary members couldn't have their `isCoordinator` modified.  Thoughts?

> * On Task what is the difference between `completeTask()` and `setComplete()`?

`completeTask()` will be a method that can be called by the `TaskEmployee()` class and `setComplete()` will allow the boolean `complete` to be modified. In the below I explain my thought process further. 

> * On `Task` you shouldn't be allowed to change if the employee has been paid after the fact. For example, your class should provide a mechanism to say "this task is completed and paid", but you should not be able to change the task back to be unpaid - this would be fraudulent.

I've made a few modifications that I believe corrects this.  First `complete` and `employeePaid` are set to false when the object is created.  When the `completeTask(float workedHours)` method is run it will check to see if the `complete` boolean is false, if it is will adjust it to true. `TaskEmployee` can then call `Task.payEmployee()` which will check if the employeePaid is true. If not it will check to see `complete` is true. If `complete` is true it will call the private method `validatePaid()` to see if `employeePaid` is true or false. If true it will throw an error. If false it will adjust the `employeePaid` to true then return the `cost` minus any deductions.

> * You marked the implementation of `Management.generateWeeklyReport()` on implementing classes, but not for `StoreOperators`

It's now added to the implemented classes for `StoreOperators`

> * `StoreOperators.changeDepartment()` is not needed, the narrative only asks for a way to allow those Employees to change department and `Employee.setDepartmentName()` already covers that case.

Removed the redundancy with gusto!

> * The UML notes required on the first review have not been added. Please see this for reference: https://image.slidesharecdn.com/introuml-1227807688880463-8/95/intro-uml-33-728.jpg?cb=1227779735

Not sure if on the note for `Task` if that should be split into multiple notes or not, but I believe this task to be complete.  Also I couldn't figure out how to attach the note link to the method I was trying to write it for. In our next meeting would love to know if you're familiar with that's done.

**Review by vinceynhz — APPROVED** [review]

**Pull request merged**
